name: Deploy Parent Portal

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build application
        run: npm run build

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 42.96.40.246
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Navigate to project directory
            cd /srv/app/frappe-pp

            # Pull latest code
            git pull origin main

            # Install dependencies (if package.json changed)
            npm ci

            # Build application
            npm run build

            # Restart nginx (if needed)
            sudo systemctl reload nginx

            echo "✅ Deployment completed successfully!"

      - name: Notify deployment status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "🎉 Deployment successful!"
          else
            echo "❌ Deployment failed!"
          fi
